Reduce number of SQL queries
coders4help/volunteer_planner pull request #375
Opened 2016-04-24 19:39 UTC by pitpalme

Helpdesk start page creates many SQL queries to render facility links.
By optimizing QuerySet fetching open shifts this information is fetched
in one query, which reduces rendering time.

2016-04-24 19:45 UTC, pitpalme commented
@christophmeissner Could you please check, if I've done nonsense? Using dummy data (`manage.py create_dummy_data 5`) it reduced number of SQL queries on helpdesk start page by almost 50% and query time by 1/3 to 1/2.

2016-04-26 21:56 UTC, asymmetric commented
Seems like you forgot to add some files/commits...

2016-04-27 21:46 UTC, pitpalme commented
@asymmetric Did I?

2016-06-04 23:29 UTC, pitpalme commented
There's now two optimization attempts:

- prefetching organizations with shifts
- prefetching news for all organizations shown and filtering it in the app, instead of multiple SQL queries, one for each organization

In total changes cut response time to roughly one half, maybe even a little less (using ```ab -n 100 -C sessionid=... .../helpdesk/```).

Performance test done in docker containers showed unoptimized version also took significantly more CPU. Still low percentage, but optimized only about one third.

Review and merge (or criticism) would be nice 😄

2016-07-15 14:39 UTC, lwm commented
I normally debug these / write tests for these optimizations with `CaptureQueriesContext`:

```
    with CaptureQueriesContext(connection) as capture:
        # use the ORM
    # have access to a count of: `capture.captured_queries`
```

My two cents ...

2022-03-20 20:50 UTC, christophmeissner requested changes
Just some litte change requests.

2022-03-20 20:50 UTC, christophmeissner commented on news/managers.py
> +# coding=utf-8
Remove encoding comment, please!

```suggestion

```

2022-03-20 20:50 UTC, christophmeissner commented on organizations/views.py
> +        context['facility'] = get_facility_details(self.object, shifts, news)  # FIXME
FIXME???

2022-03-20 20:50 UTC, christophmeissner commented on scheduler/managers.py
>  # coding: utf-8
Remove
```suggestion

```

2022-03-20 20:54 UTC, christophmeissner approved these changes

2022-03-24 23:04 UTC, closed without merging