Django4
coders4help/volunteer_planner pull request #466
Opened 2022-03-18 14:06 UTC by Doca

Resolve #438

2022-03-18 22:26 UTC, pitpalme approved these changes
Good job, so far.
It filters, it remembers.

Alas - no sunshine without some slight rain.
None of this is a merge-blocker for now, because having it ready to be manually tested already is valuable. But as a reminder I'd like to note it nonetheless.

- let's not forget to remove "console.log()" calls, my DevTools console almost went crazy
- let's think about, whether it makes sense, to filter "Areas" according to selected countries
- there's l10n fixes necessary, but I havent's checked yet, wether it's untranslated strings or a more general issue: /helpdesk/ is shown localised, but filter labels are "English only".

2022-03-19 06:59 UTC, christophmeissner requested changes

2022-03-19 06:59 UTC, christophmeissner commented on scheduler/templates/helpdesk.html
> +                        console.log(item)
Remove debug logging

2022-03-19 07:36 UTC, christophmeissner commented
I wonder why this was not based onto `develop` but `django4` instead. It looks like as if it will work with Django 2 as well.

2022-03-19 08:28 UTC, Doca commented on scheduler/templates/helpdesk.html
> +                        console.log(item)
thx

2022-03-19 08:28 UTC, merged

2022-03-19 08:41 UTC, christophmeissner commented on scheduler/templates/helpdesk.html
> +                        console.log(item)
?