Improve test factories and dummy data
coders4help/volunteer_planner pull request #467
Opened 2022-03-18 22:58 UTC by pitpalme

2022-03-19 08:09 UTC, christophmeissner commented on tests/factories.py
> +    email = LazyAttribute(lambda o: '%s@example.com' % o.last_name)
Replace with an f-string?

```suggestion
    email = LazyAttribute(lambda o: f"{o.last_name}@example.com")
```

2022-03-19 08:09 UTC, christophmeissner commented on tests/factories.py
>      ending_time = datetime(2016, 2, 13, 20, 0)
Change to datetime.now or sth. in that ballpark?

2022-03-20 11:58 UTC, pitpalme commented on scheduler/management/commands/create_dummy_data.py
> +                for clazz in [RegistrationProfile, ShiftHelper, Shift, UserAccount, Task, Workplace, Facility,
Caught me - not yet a djangonaut, but can't deny my heritage. :D

2022-03-20 11:58 UTC, pitpalme commented on scheduler/management/commands/create_dummy_data.py
> +                for clazz in [RegistrationProfile, ShiftHelper, Shift, UserAccount, Task, Workplace, Facility,
It's gonna be changed and out of curiosity: what's the difference in handling / behaviour?
Is it only about "not being able to alter this anonymous enlisting of values"?

2022-03-20 12:02 UTC, pitpalme commented on tests/factories.py
> +    email = LazyAttribute(lambda o: '%s@example.com' % o.last_name)
*meeehhhh* didn't touch too much code, but: valid point.

2022-03-20 12:17 UTC, pitpalme commented on scheduler/management/commands/create_dummy_data.py
> +                for clazz in [RegistrationProfile, ShiftHelper, Shift, UserAccount, Task, Workplace, Facility,
Changed

2022-03-20 12:20 UTC, christophmeissner commented on scheduler/management/commands/create_dummy_data.py
> +                for clazz in [RegistrationProfile, ShiftHelper, Shift, UserAccount, Task, Workplace, Facility,
In fact, parenthesis for enumeration of model classes can be omitted entirely and python will handle it as a tuple. Parenthesis only become required, when the enumeration is formatted to span multiple lines. 

However, my rule of thumb is: when it's not required to be mutable, it should not be mutable. Most of the times, mutable objects are at least slightly more expensive. This article breaks the implications of (im-)mutability pretty good in a few paragraphs: https://medium.datadriveninvestor.com/mutable-and-immutable-python-2093deeac8d9

2022-03-20 12:29 UTC, christophmeissner requested changes
Just one more thing ;-)

2022-03-20 12:29 UTC, christophmeissner commented on tests/factories.py
> +    name = Sequence(lambda n: "fWorkplace {n}")
Typo in f-string
```suggestion
    name = Sequence(lambda n: f"Workplace {n}")
```

2022-03-20 14:15 UTC, pitpalme commented
> Just one more thing ;-)

*duuuhh* another kind of "one-off" 😆

2022-03-20 16:19 UTC, christophmeissner approved these changes

2022-03-20 18:01 UTC, merged