Add more `flake8` checks (aka. stricter code linting)
coders4help/volunteer_planner pull request #612
Opened 2022-04-13 07:42 UTC by christophmeissner

Adds the following flake8 plugins:

* flake8-bugbear
* flake8-comprehensions
* flake8-mutable
* flake8-print
* flake8-simplify

2022-04-13 13:32 UTC, pitpalme submitted a review, later dismissed

2022-04-15 21:13 UTC, pitpalme requested changes

2022-04-15 21:13 UTC, pitpalme commented on common/brace_format_logging.py
> +    )
Some dev leftover for manual testing?

2022-04-15 21:13 UTC, pitpalme commented on tests/scheduler/test_models.py
> +    grace = args[0] if args else timedelta(hours=1)
```suggestion
    grace,
):
    grace = grace if grace is not None else timedelta(hours=1)
```

as in [scheduler/signals.py](https://github.com/coders4help/volunteer_planner/pull/612/files#diff-8f845bde33120acc737b16f82259b3722d893a9dbefed2642bdc9a13d3e2a83e)?

2022-04-15 21:13 UTC, pitpalme commented on common/static_file_compressor.py
> +                with gzip.open("{}.gz".format(path), "wb") as f_out:  # noqa: SIM117
```suggestion
                with gzip.open(f"{path}.gz", "wb") as f_out:  # noqa: SIM117
```

2022-04-15 21:36 UTC, christophmeissner commented on tests/scheduler/test_models.py
> +    grace = args[0] if args else timedelta(hours=1)
thats doesn't work, because `None` is actually a valid value (it was like this before, but pytest said "no!")

2022-04-15 21:39 UTC, christophmeissner commented on common/brace_format_logging.py
> +    )
Kind of demo, documentation and test... I wasn't sure how to actually test loggers. Suggestions welcome!

2022-04-15 21:50 UTC, pitpalme requested changes

2022-04-15 21:50 UTC, pitpalme commented on common/brace_format_logging.py
> +
```suggestion
    """
    This is for demonstration purpose and to run quick tests.
    """
```

2022-04-15 21:52 UTC, pitpalme commented on tests/scheduler/test_models.py
> +    grace = args[0] if args else timedelta(hours=1)
Gosh - you're right. 🙈 
Thanks for the re-review.

2022-04-15 21:57 UTC, pitpalme requested changes

2022-04-15 21:57 UTC, pitpalme commented on common/brace_format_logging.py
> +    class SomeObj:
```suggestion
if __name__ == "__main__":
    """
    This is for demonstration purpose and to run quick tests.
    """

    class SomeObj:
```

2022-04-15 22:05 UTC, pitpalme approved these changes

2022-04-15 22:05 UTC, merged